


remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# pages-themes/architect@v0.2.0

# pages-themes/minimal@v0.2.0

# pages-themes/dinky@v0.2.0 # prefered choice

# pages-themes/hacker@v0.2.0

# pages-themes/leap-day@v0.2.0 #there is a thing called view on github, after clicking people can edit the file?

# pages-themes/merlot@v0.2.0 

# pages-themes/midnight@v0.2.0 # black backgroud white words

# pages-themes/slate@v0.2.0 # prefered

#pages-themes/modernist@v0.2.0



